modLoader = "kotlinforforge"
loaderVersion = "${k4fVersionRange}"
license = "${modLicense}"
issueTrackerURL = "${modIssueTracker}"

[[mods]]
modId = "${modId}"
version = "${modVersion}"
displayName = "${modName}"
updateJSONURL = "${modUpdateUrl}"
displayURL = "${modDisplayUrl}"
logoFile = "${modLogo}"
credits = "${modCredits}"
authors = "${modAuthors}"
description = "${modDescription}"

[[dependencies.${modId}]]
modId = "neoforge"
type = "required"
versionRange = "${neoForgeVersionRange}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${modId}]]
modId = "minecraft"
type = "required"
versionRange = "${minecraftVersionRange}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${modId}]]
modId = "kotlinforforge"
type = "required"
versionRange = "${k4fVersionRange}"
ordering = "NONE"
side = "BOTH"